class Autogenerated {
  String message;
  String error;
  Data data;

  Autogenerated({this.message, this.error, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    error = json['error'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  String country;
  String panImage;
  String adhaarImage;
  String adhaarBackImage;
  bool updateMainNetBalance;
  bool kycApproved;
  String sId;
  int phone;
  String fname;
  String mname;
  String lname;
  String email;
  String pin;
  String accType;
  String bankAccNo;
  String ifscCode;

  Data(
      {this.country,
        this.panImage,
        this.adhaarImage,
        this.adhaarBackImage,
        this.updateMainNetBalance,
        this.kycApproved,
        this.sId,
        this.phone,
        this.fname,
        this.mname,
        this.lname,
        this.email,
        this.pin,
        this.accType,
        this.bankAccNo,
        this.ifscCode});

  Data.fromJson(Map<String, dynamic> json) {
    country = json['country'];
    panImage = json['panImage'];
    adhaarImage = json['adhaarImage'];
    adhaarBackImage = json['adhaarBackImage'];
    updateMainNetBalance = json['updateMainNetBalance'];
    kycApproved = json['kycApproved'];
    sId = json['_id'];
    phone = json['phone'];
    fname = json['fname'];
    mname = json['mname'];
    lname = json['lname'];
    email = json['email'];
    pin = json['pin'];
    accType = json['accType'];
    bankAccNo = json['bankAccNo'];
    ifscCode = json['ifscCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['country'] = this.country;
    data['panImage'] = this.panImage;
    data['adhaarImage'] = this.adhaarImage;
    data['adhaarBackImage'] = this.adhaarBackImage;
    data['updateMainNetBalance'] = this.updateMainNetBalance;
    data['kycApproved'] = this.kycApproved;
    data['_id'] = this.sId;
    data['phone'] = this.phone;
    data['fname'] = this.fname;
    data['mname'] = this.mname;
    data['lname'] = this.lname;
    data['email'] = this.email;
    data['pin'] = this.pin;
    data['accType'] = this.accType;
    data['bankAccNo'] = this.bankAccNo;
    data['ifscCode'] = this.ifscCode;
    return data;
  }
}