class AutogeneratedWallet {
  String message;
  String error;
  Data data;

  AutogeneratedWallet({this.message, this.error, this.data});

  AutogeneratedWallet.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    error = json['error'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  String sId;
  var bTCBalance;
  var eTHBalance;
  var uSDTBalance;
  var iNRBalance;
  var bCHBalance;
  var cRMTBalance;

  Data(
      {this.sId,
        this.bTCBalance,
        this.eTHBalance,
        this.uSDTBalance,
        this.iNRBalance,
        this.bCHBalance,
        this.cRMTBalance});

  Data.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    bTCBalance = json['BTCBalance'];
    eTHBalance = json['ETHBalance'];
    uSDTBalance = json['USDTBalance'];
    iNRBalance = json['INRBalance'];
    bCHBalance = json['BCHBalance'];
    cRMTBalance = json['CRMTBalance'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['BTCBalance'] = this.bTCBalance;
    data['ETHBalance'] = this.eTHBalance;
    data['USDTBalance'] = this.uSDTBalance;
    data['INRBalance'] = this.iNRBalance;
    data['BCHBalance'] = this.bCHBalance;
    data['CRMTBalance'] = this.cRMTBalance;
    return data;
  }
}
