import 'package:flutter/material.dart';
import 'package:fyn_zon/Asset/assets.dart';
import 'package:fyn_zon/animation/FadeAnimation.dart';
import 'package:fyn_zon/bankAccount.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:fyn_zon/orderHistory.dart';
import 'package:fyn_zon/paymentOption.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';
import 'package:page_transition/page_transition.dart';
import 'package:fyn_zon/tokenPass.dart';
import 'package:fyn_zon/signup.dart';
import 'package:fyn_zon/mainscreen.dart';
import 'package:fyn_zon/updateProfile.dart';
import 'mainApi.dart';
import 'kyc.dart';
import 'login.dart';
class Autogenerated {
  String message;
  String error;
  Data data;

  Autogenerated({this.message, this.error, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    error = json['error'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  String country;
  String sId;
  int phone;
  String fname;
  String lname;
  String email;
  String pin;
  String address;
  String adhaarNumber;
  String city;
  bool kycApproved;
  String dob;
  String panNumber;
  String pinCode;
  String state;
  String nationality;

  Data(
      {this.country,
        this.sId,
        this.phone,
        this.fname,
        this.lname,
        this.email,
        this.pin,
        this.address,
        this.adhaarNumber,
        this.city,
        this.kycApproved,
        this.dob,
        this.panNumber,
        this.pinCode,
        this.state,
        this.nationality});

  Data.fromJson(Map<String, dynamic> json) {
    country = json['country'];
    sId = json['_id'];
    phone = json['phone'];
    fname = json['fname'];
    lname = json['lname'];
    email = json['email'];
    pin = json['pin'];
    address = json['address'];
    adhaarNumber = json['adhaarNumber'];
    city = json['city'];
    kycApproved = json['kycApproved'];
    dob = json['dob'];
    panNumber = json['panNumber'];
    pinCode = json['pinCode'];
    state = json['state'];
    nationality = json['nationality'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['country'] = this.country;
    data['_id'] = this.sId;
    data['phone'] = this.phone;
    data['fname'] = this.fname;
    data['lname'] = this.lname;
    data['email'] = this.email;
    data['pin'] = this.pin;
    data['address'] = this.address;
    data['adhaarNumber'] = this.adhaarNumber;
    data['kycApproved'] = this.kycApproved;
    data['city'] = this.city;
    data['dob'] = this.dob;
    data['panNumber'] = this.panNumber;
    data['pinCode'] = this.pinCode;
    data['state'] = this.state;
    data['nationality'] = this.nationality;
    return data;
  }
}
class Dbar extends StatefulWidget {
  @override
  _DbarState createState() => _DbarState();
}

class _DbarState extends State<Dbar> {

  Future<void> main() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
   // prefs?.clear();
    prefs.remove('token');
    prefs.remove('userid');
    Navigator.pop(context);
    Navigator.pushReplacement(
      context,
      PageTransition(
        type: PageTransitionType.leftToRight,
        child: MainScreenPage(),
      ),
    );
        (Route route) => false;
  }
  Future<void> logout() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    // prefs?.clear();
    prefs.remove('token');
    prefs.remove('userid');
    Fluttertoast.showToast(
        msg: "User Logout",
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
        timeInSecForIosWeb: 1
    );
    Navigator.pop(context);
    Navigator.pushReplacement(
      context,
      PageTransition(
        type: PageTransitionType.leftToRight,
        child: LoginScreen(),
      ),
    );
        (Route route) => false;
  }
  Autogenerated futureAlbum;
  @override
  void initState() {
    super.initState();
    fetchAlbum1();
    setState(() {

    });
  }
  var userid;
  Future<void> fetchAlbum1() async {
    /* var data = {

    };*/
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      userid = prefs.getString('userid');
    });
      var apiData = {
      "url": AuthToken.api + "/" + "client/userDetails/"+ prefs.getString('token'),
      //"data": data
    };
    ApiClass.getApiCall(apiData, (onSuccess) {
      print(onSuccess.toString());
      futureAlbum = Autogenerated.fromJson(jsonDecode(onSuccess['response']));
      //print("walletqrcode>>>>>>> " + futureAlbum.data.phone.toString());
      print("walletqrcode>>>>>>> " + futureAlbum.message.toString());

      setState(() {});
    }, (onError) {
      print("Error working with the api");
      logout();

    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF18222C),
      appBar: AppBar(
        backgroundColor: Color(0xFF18222C),
        title: Text('Settings',style: TextStyle(
            color: Colors.white
        ),),
      ),
      body: Container(
          child: userid == null ?
          Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
            color: Color(0xFF18222C),
            child:  Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                GestureDetector(
                  onTap:(){
                    Navigator.pop(context);
                    Navigator.push(
                      context,
                      PageTransition(
                        type: PageTransitionType.leftToRight,
                        child: LoginScreen(),
                      ),
                    );
                  },
                  child: Container(
                    color: Color(0xFF233446),
                    margin: EdgeInsets.only(top: 20),
                    padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                    child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Text('Login',
                            style: TextStyle(color: Colors.white, fontSize: 15),
                          ),
                        ]

                    ),
                  ),
                ),
                GestureDetector(
                  onTap:(){
                    Navigator.pop(context);
                    Navigator.push(
                      context,
                      PageTransition(
                        type: PageTransitionType.leftToRight,
                        child: SignupPage(),
                      ),
                    );
                  },
                  child: Container(
                    color: Color(0xFF233446),
                    margin: EdgeInsets.only(top: 1),
                    padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                    child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Text('Signup',
                            style: TextStyle(color: Colors.white, fontSize: 15),
                          ),
                        ]

                    ),
                  ),
                ),

              ],
            ),
          ) :
          /*futureAlbum.message == "Invalid token in the request"
          ? main()
              :*/
          FutureBuilder<Autogenerated>(
              builder: (context, snapshot){
                if (futureAlbum != null) {
                  String name = futureAlbum.data.fname;
                  String lastname = futureAlbum.data.lname;
                  String email = futureAlbum.data.email;
                  String city = futureAlbum.data.city;
                  String state = futureAlbum.data.state;
                  String nationality = futureAlbum.data.nationality;
                  String pin = futureAlbum.data.pin;
                  String pincode = futureAlbum.data.pinCode;
                  String phone = futureAlbum.data.phone.toString();
                  return Container(
                    color: Color(0xFF18222C),
                    child: ListView(
                      children: <Widget>[
                        GestureDetector(
                          onTap: () {
                            setState(() {
                              showModalBottomSheet(

                                isScrollControlled: true,
                                context: context,
                                builder: (context) =>
                                    Wrap(children: [
                                      //UserProfile()
                                      Container(
                                        margin: EdgeInsets.all(15),
                                        width: MediaQuery
                                            .of(context)
                                            .size
                                            .width,
                                        height: MediaQuery
                                            .of(context)
                                            .size
                                            .height / 2.7,
                                        child: SingleChildScrollView(
                                          child: Container(
                                            color: Colors.white,
                                            child: Card(
                                              elevation: 2,
                                              child: Container(
                                                padding: EdgeInsets.only(
                                                    bottom: 20),

                                                child: Column(
                                                  mainAxisAlignment: MainAxisAlignment
                                                      .center,
                                                  children: <Widget>[
                                                    FadeAnimation(
                                                      1.5,
                                                      GestureDetector(
                                                        onTap: () {
                                                          Navigator.pop(
                                                              context);
                                                        },
                                                        child: Align(
                                                          alignment: Alignment
                                                              .topRight,
                                                          child: Container(
                                                            //width: 70,
                                                              padding: EdgeInsets
                                                                  .all(10),
                                                              color: Colors
                                                                  .white,
                                                              margin: EdgeInsets
                                                                  .only(top: 3,
                                                                  right: 2),
                                                              alignment: Alignment
                                                                  .topRight,
                                                              child: Icon(
                                                                Icons.close,
                                                                color: Colors
                                                                    .black,
                                                              )
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    FadeAnimation(
                                                      1.5,
                                                      Container(
                                                        child: Text(
                                                          'User Profile',
                                                          style: TextStyle(
                                                            fontSize: 20,
                                                            color: Colors.black,
                                                            //fontWeight: FontWeight.bold
                                                          ),
                                                        ),
                                                      ),
                                                    ),

                                                    FadeAnimation(
                                                      1.5,
                                                      Container(
                                                        padding: EdgeInsets
                                                            .fromLTRB(15, 40,
                                                            20, 5),
                                                        child: Row(
                                                          mainAxisAlignment: MainAxisAlignment
                                                              .spaceBetween,
                                                          children: <Widget>[
                                                            Container(
                                                              child: Text(
                                                                'Contact Number*',
                                                                style: TextStyle(
                                                                    color: Colors
                                                                        .black,
                                                                    fontSize: 16,
                                                                    fontWeight: FontWeight
                                                                        .w400
                                                                ),),
                                                            ),
                                                            Container(
                                                              margin: EdgeInsets
                                                                  .only(
                                                                  left: 10),
                                                              child: Text(
                                                                futureAlbum.data
                                                                    .phone
                                                                    .toString(),
                                                                style: TextStyle(
                                                                  fontSize: 18,
                                                                  color: Colors
                                                                      .blueGrey,
                                                                  //fontWeight: FontWeight.bold
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                    FadeAnimation(
                                                      2.5,
                                                      Container(
                                                        padding: EdgeInsets
                                                            .fromLTRB(15, 15,
                                                            20, 5),
                                                        child: Row(
                                                          mainAxisAlignment: MainAxisAlignment
                                                              .spaceBetween,
                                                          children: <Widget>[
                                                            Container(
                                                              child: Text(
                                                                'User Name*',
                                                                style: TextStyle(
                                                                    color: Colors
                                                                        .black,
                                                                    fontSize: 16,
                                                                    fontWeight: FontWeight
                                                                        .w400
                                                                ),),
                                                            ),
                                                            Container(
                                                              alignment: Alignment
                                                                  .center,
                                                              child: Icon(
                                                                Icons.person,
                                                                color: Colors
                                                                    .white,
                                                              ),
                                                            ),
                                                            Container(
                                                              child: Row(
                                                                children: <
                                                                    Widget>[
                                                                  Container(
                                                                    margin: EdgeInsets
                                                                        .only(
                                                                        left: 10),
                                                                    child: Text(
                                                                      futureAlbum
                                                                          .data
                                                                          .fname,
                                                                      style: TextStyle(
                                                                        fontSize: 18,
                                                                        color: Colors
                                                                            .blueGrey,
                                                                        //fontWeight: FontWeight.bold
                                                                      ),
                                                                    ),
                                                                  ),
                                                                  Container(
                                                                    margin: EdgeInsets
                                                                        .only(
                                                                        left: 5),
                                                                    child: Text(
                                                                      futureAlbum
                                                                          .data
                                                                          .lname,
                                                                      style: TextStyle(
                                                                        fontSize: 18,
                                                                        color: Colors
                                                                            .blueGrey,
                                                                        //fontWeight: FontWeight.bold
                                                                      ),
                                                                    ),
                                                                  ),
                                                                ],
                                                              ),
                                                            )
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                    FadeAnimation(
                                                      2.5,
                                                      Container(

                                                        padding: EdgeInsets
                                                            .fromLTRB(15, 15,
                                                            20, 5),
                                                        child: Row(
                                                          mainAxisAlignment: MainAxisAlignment
                                                              .spaceBetween,
                                                          children: <Widget>[
                                                            Container(
                                                              child: Text(
                                                                'Email ID*',
                                                                style: TextStyle(
                                                                    color: Colors
                                                                        .black,
                                                                    fontSize: 16,
                                                                    fontWeight: FontWeight
                                                                        .w400
                                                                ),),
                                                            ),
                                                            Expanded(
                                                              child: Container(
                                                                margin: EdgeInsets
                                                                    .only(
                                                                    left: 10),
                                                                child: Text(
                                                                  futureAlbum
                                                                      .data
                                                                      .email,
                                                                  textAlign: TextAlign
                                                                      .right,
                                                                  overflow: TextOverflow
                                                                      .ellipsis,
                                                                  maxLines: 2,

                                                                  style: TextStyle(
                                                                    fontSize: 18,
                                                                    color: Colors
                                                                        .blueGrey,
                                                                    //fontWeight: FontWeight.bold
                                                                  ),
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),

                                    ]),
                              );
                              /* Navigator.pop(context);
                                 Navigator.push(
                                   context,
                                   MaterialPageRoute(
                                     builder: (context) => UserProfile(),
                                   ),
                                 );*/
                            });
                            /*Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                    builder: (context) => UserProfile(),
                                  ),
                                );*/
                          },
                          child: Container(
                            color: Color(0xFF233446),
                            margin: EdgeInsets.only(top: 25),
                            padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment
                                    .spaceBetween,
                                children: <Widget>[
                                  Container(
                                    child: Row(
                                      children: <Widget>[
                                        Text(futureAlbum.data.fname,
                                          style: TextStyle(color: Colors.white,
                                              fontSize: 15),
                                        ),
                                        Container(
                                          margin: EdgeInsets.only(left: 5),
                                          child: Text(futureAlbum.data.lname,
                                            style: TextStyle(
                                                color: Colors.white,
                                                fontSize: 15),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ]

                            ),
                          ),

                          /*UserAccountsDrawerHeader(
                                accountName: Row(
                                  children: [
                                    FadeAnimation(
                                      1.5,
                                      Container(
                                          margin: EdgeInsets.only(right: 5),
                                          child: Text(futureAlbum.data.fname)),
                                    ),
                                    FadeAnimation(
                                        1.5, Text(futureAlbum.data.lname)),
                                  ],
                                ),
                                accountEmail: FadeAnimation(
                                    1.5,Text(futureAlbum.data.email)),
                                currentAccountPicture: FadeAnimation(
                                  1.5, CircleAvatar(
                                  backgroundColor:
                                  Theme.of(context).platform == TargetPlatform.iOS
                                      ? Colors.blue
                                      : Colors.white,
                                  child: Text(
                                    futureAlbum.data.fname[0],
                                    style: TextStyle(fontSize: 40.0),
                                  ),
                                ),
                                ),
                              ),*/
                        ),
                        Container(
                          color: Color(0xFF233446),
                          margin: EdgeInsets.only(top: 0.5),
                          padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                          child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: <Widget>[
                                Text(futureAlbum.data.email,
                                  style: TextStyle(
                                      color: Colors.white, fontSize: 15),
                                ),
                              ]

                          ),
                        ),
                        GestureDetector(
                          onTap: () {
                            Navigator.pop(context);
                            Navigator.push(
                              context,
                              PageTransition(
                                type: PageTransitionType.leftToRight,
                                child: UpdateProfile(
                                  name,
                                  lastname,
                                  state,
                                  nationality,
                                  email,
                                  city,
                                  pincode,
                                  pin,
                                  phone,),
                              ),
                            );
                          },
                          child: FadeAnimation(
                            1.5, Container(
                            margin: EdgeInsets.only(top: 10),
                            color: Color(0xFF233446),
                            padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment
                                    .spaceBetween,
                                children: <Widget>[
                                  Text(
                                    'Update Profile',
                                    style: TextStyle(
                                        color: Colors.white, fontSize: 15),
                                  ),
                                  Icon(
                                    Icons.chevron_right, color: Colors.white,),
                                ]

                            ),
                          ),
                          ),
                        ),
                        GestureDetector(
                          onTap: () {
                            Navigator.pop(context);
                            Navigator.push(
                              context,
                              PageTransition(
                                type: PageTransitionType.leftToRight,
                                child: Assets(),
                              ),
                            );
                          },
                          child: FadeAnimation(
                            1.5, Container(
                            margin: EdgeInsets.only(top: 10),
                            color: Color(0xFF233446),
                            padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment
                                    .spaceBetween,
                                children: <Widget>[
                                  Text(
                                    'Assets',
                                    style: TextStyle(
                                        color: Colors.white, fontSize: 15),
                                  ),
                                  Icon(
                                    Icons.chevron_right, color: Colors.white,),
                                ]

                            ),
                          ),
                          ),
                        ),
                        GestureDetector(
                          onTap: () {
                            Navigator.pop(context);
                            Navigator.push(
                              context,
                              PageTransition(
                                type: PageTransitionType.leftToRight,
                                child: OrderHistory(),
                              ),
                            );
                          },
                          child: FadeAnimation(
                            1.5, Container(
                            margin: EdgeInsets.only(top: 10),
                            color: Color(0xFF233446),
                            padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment
                                    .spaceBetween,
                                children: <Widget>[
                                  Text(
                                    'Reports',
                                    style: TextStyle(
                                        color: Colors.white, fontSize: 15),
                                  ),
                                  Icon(
                                    Icons.chevron_right, color: Colors.white,),
                                ]

                            ),
                          ),
                          ),
                        ),
                        GestureDetector(
                          onTap: () {
                            if (futureAlbum.data.kycApproved == true) {
                              return showDialog(
                                  context: context,
                                  barrierDismissible: false,
                                  builder: (BuildContext context) {
                                    return AlertDialog(
                                      backgroundColor: Colors.white,
                                      title: Text("Kyc Approved !"),
                                      content: Text(
                                          "Your KYC has already approved. "),
                                      actions: <Widget>[
                                        FlatButton(
                                          child: Text("Ok", style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 18
                                          ),),
                                          onPressed: () {
                                            Navigator.of(context).pop();
                                          },
                                        ),
                                      ],
                                    );
                                  }
                              );
                            }
                            else {
                              print("lalit" +
                                  futureAlbum.data.kycApproved.toString());
                              Navigator.pop(context);
                              Navigator.push(
                                context,
                                PageTransition(
                                  type: PageTransitionType.leftToRight,
                                  child: KYC(
                                    name, lastname, state, city, pincode,),
                                ),
                              );
                            }
                          },
                          child: FadeAnimation(
                            1.5, Container(
                            margin: EdgeInsets.only(top: 10),
                            color: Color(0xFF233446),
                            padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment
                                    .spaceBetween,
                                children: <Widget>[
                                  Text(
                                    'KYC',
                                    style: TextStyle(
                                        color: Colors.white, fontSize: 15),
                                  ),
                                  Icon(
                                    Icons.chevron_right, color: Colors.white,),
                                ]

                            ),
                          ),
                          ),
                        ),
                        GestureDetector(
                          onTap: () {
                            if (futureAlbum.data.kycApproved == true) {
                              return showDialog(
                                  context: context,
                                  barrierDismissible: false,
                                  builder: (BuildContext context) {
                                    return AlertDialog(
                                      backgroundColor: Colors.white,
                                      title: Text("Kyc Approved !"),
                                      content: Text(
                                          "Your KYC has already approved. "),
                                      actions: <Widget>[
                                        FlatButton(
                                          child: Text("Ok", style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 18
                                          ),),
                                          onPressed: () {
                                            Navigator.of(context).pop();
                                          },
                                        ),
                                      ],
                                    );
                                  }
                              );
                            } else {
                              Navigator.pop(context);
                              Navigator.push(
                                context,
                                PageTransition(
                                  type: PageTransitionType.leftToRight,
                                  child: PaymentOption(),
                                ),
                              );
                            }
                          },
                          child: FadeAnimation(
                            1.5, Container(
                            margin: EdgeInsets.only(top: 10),
                            color: Color(0xFF233446),
                            padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment
                                    .spaceBetween,
                                children: <Widget>[
                                  Text(
                                    'Bank Account Details',
                                    style: TextStyle(
                                        color: Colors.white, fontSize: 15),
                                  ),
                                  Icon(
                                    Icons.chevron_right, color: Colors.white,),
                                ]

                            ),
                          ),
                          ),
                        ),
                        GestureDetector(
                          onTap: () {
                            showDialog(
                                context: context,
                                barrierDismissible: false,
                                builder: (BuildContext context) {
                                  return AlertDialog(
                                    backgroundColor: Colors.blueGrey,
                                    title: Text("Confirm Logout"),
                                    content: Text(
                                        "Are you sure you want to logout?"),
                                    actions: <Widget>[
                                      FlatButton(
                                        child: Text("YES", style: TextStyle(
                                            color: Colors.white
                                        ),),
                                        onPressed: () {
                                          main();
                                        },
                                      ),
                                      FlatButton(
                                        child: Text("NO", style: TextStyle(
                                            color: Colors.white
                                        ),),
                                        onPressed: () {
                                          Navigator.of(context).pop();
                                        },
                                      )
                                    ],
                                  );
                                }
                            );
                          },
                          child: FadeAnimation(
                            1.5, Container(
                            margin: EdgeInsets.only(top: 10),
                            color: Color(0xFF233446),
                            padding: EdgeInsets.fromLTRB(15, 10, 20, 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment
                                    .spaceBetween,
                                children: <Widget>[
                                  Text(
                                    'Logout',
                                    style: TextStyle(
                                        color: Colors.redAccent, fontSize: 15),
                                  ),
                                  Icon(Icons.chevron_right, color: Colors.red,),
                                ]

                            ),
                          ),
                          ),
                        ),
                      ],
                    ),
                  );
                }
                else if (snapshot.hasError) {
                  return Text("${snapshot.error}");
                }
                return Container(
                    alignment: Alignment.center,
                    height: MediaQuery.of(context).size.height,
                    width: MediaQuery.of(context).size.width,
                    // margin: EdgeInsets.only(top: 80),
                    child: CircularProgressIndicator(backgroundColor: Color(0xFF18222C),));
              }
          )
      )
    );

  }
}
