import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:fyn_zon/paymentOption.dart';
import './second_withdrawal.dart';
import 'package:page_transition/page_transition.dart';
import 'package:fyn_zon/tokenPass.dart';
import 'dart:convert';
import 'package:fyn_zon/updateProfile.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/material.dart';
import 'package:fyn_zon/animation/FadeAnimation.dart';
import 'package:fyn_zon/tokenPass.dart';
import 'package:fyn_zon/mainscreen.dart';
import 'mainApi.dart';
import 'login.dart';
class Autogenerated {
  String message;
  String error;
  Data data;

  Autogenerated({this.message, this.error, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    error = json['error'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  var bankAccNo;
  String ifscCode;
  String accType;

  Data(
      {
        this.bankAccNo,
        this.ifscCode,
        this.accType});

  Data.fromJson(Map<String, dynamic> json) {
    bankAccNo = json['bankAccNo'];
    //sId = json['_id'];
    ifscCode = json['ifscCode'];
    accType = json['accType'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['bankAccNo'] = this.bankAccNo;
    data['ifscCode'] = this.ifscCode;
    data['accType'] = this.accType;
    return data;
  }
}

class FirstWithdrawPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return FirstWithdrawPageState();
  }
}

class FirstWithdrawPageState extends State<FirstWithdrawPage> {
  Autogenerated futureAlbum;
  @override
  void initState() {
    super.initState();
    fetchAlbum();

  }

  fetchAlbum() async {
    /* var data = {

    };*/
    var prefs = await SharedPreferences.getInstance();
    var token = prefs.getString("token");
    AuthToken.authtoken = token;
    var apiData = {
      "url": AuthToken.api + "/" + "client/userDetails/" + AuthToken.authtoken,
      //"data": data
    };
    ApiClass.getApiCall(apiData, (onSuccess) {
      print(onSuccess.toString());
      futureAlbum = Autogenerated.fromJson(jsonDecode(onSuccess['response']));
      print("acctype>>>>>>> " + futureAlbum.data.bankAccNo.toString());
      setState(() {});
    }, (onError) {
      print("Error working with the api");
    });
  }
  @override
  Widget build(BuildContext context) {
    return  WillPopScope(
      onWillPop: () {
        Navigator.pop(context);
      },
      child:  AuthToken.userid == null ?
      GestureDetector(
        onTap: (){
          Navigator.pop(context);
          Navigator.push(
            context,
            PageTransition(
              type: PageTransitionType.leftToRight,
              child: LoginScreen(),
            ),
          );
        },
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          // color: Color(0xFF18222C),
          child:  Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Container(
                width: 100,
                alignment: Alignment.center,
                padding: EdgeInsets.all(10),
                child: Text(
                  'Login ',
                  style: TextStyle(color: Colors.white, fontSize: 18,),
                ),
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.all(Radius.circular(10)),
                    color: Colors.blue,
                    border: Border.all(color: Colors.blue)),
              ),

            ],
          ),
        ),
      )
      :SingleChildScrollView(
          child: FutureBuilder<Autogenerated>(
            //future: futureAlbum,
            builder: (context, snapshot) {
              if (futureAlbum != null) {
                return Container(
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height/1.14,
                  color: Colors.white,
                  padding: EdgeInsets.all(10.0),
                  // width: double.infinity,
                  child: Column(
                    // mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Container(
                            padding: EdgeInsets.only(left: 5),
                            child: Text(
                              "Instant Withdrawal (Recommended)",
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                  fontSize: 15,
                                  color: Colors.grey[700],
                                  fontWeight: FontWeight.bold),
                            ),
                          ),
                          GestureDetector(
                            onTap: ()=> Navigator.pop(context),
                            child: Container(
                              // alignment: Alignment.topRight,
                              child: Icon(Icons.close,color: Colors.grey,),
                            ),
                          ),

                        ],
                      ),
                      Card(
                        elevation: 4,
                        margin: EdgeInsets.all(10),
                        child: Column(
                          children: [

                            SizedBox(
                              height: 20,
                            ),
                            Column(
                              children: [
                                Row(
                                  children: [
                                    Padding(
                                      padding: EdgeInsets.only(left: 20.0),
                                      child: Image.asset(
                                        "assets/images/fz_bank.png",
                                        scale: 2.9,
                                      ),
                                    ),
                                    Align(
                                      alignment: Alignment.topLeft,
                                      child: Padding(
                                        padding: EdgeInsets.only(left: 8.0),
                                        child: Text(
                                          "Withdraw to this bank account",
                                          style: TextStyle(
                                              fontSize: 12,
                                              color: Colors.redAccent,
                                              fontWeight: FontWeight.bold),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                                Container(
                                  padding: EdgeInsets.all(20),
                                  //margin: EdgeInsets.only(top: 10),
                                  child: Column(
                                    children: <Widget>[
                                      Row(
                                        children: [
                                          Container(
                                            child: Text('Account Number',style: TextStyle(
                                                color: Colors.grey[400],
                                                fontSize: 13
                                            ),),
                                          ),
                                          Container(
                                            padding: EdgeInsets.only(left: 40),
                                            child: Text(futureAlbum.data.bankAccNo.toString(),style: TextStyle(
                                                color: Colors.black,
                                                letterSpacing: 1.0,
                                                fontSize: 14
                                            ),),
                                          )
                                        ],
                                      ),
                                      Container(
                                        margin: EdgeInsets.only(top: 10),
                                        child: Row(
                                          children: [
                                            Container(
                                              child: Text('IFSC Code',style: TextStyle(
                                                  color: Colors.grey[400],
                                                  fontSize: 13
                                              ),),
                                            ),
                                            Container(
                                              padding: EdgeInsets.only(left: 72),
                                              child: Text(futureAlbum.data.ifscCode,style: TextStyle(
                                                  color: Colors.black,
                                                  letterSpacing: 1.0,
                                                  fontSize: 14
                                              ),),
                                            )
                                          ],
                                        ),
                                      ),
                                      Container(
                                        margin: EdgeInsets.only(top: 10),
                                        child: Row(
                                          children: [
                                            Container(
                                              child: Text('Account Type',style: TextStyle(
                                                  color: Colors.grey[400],
                                                  fontSize: 13
                                              ),),
                                            ),
                                            Container(
                                              padding: EdgeInsets.only(left: 55),
                                              child: Text(futureAlbum.data.accType,style: TextStyle(
                                                  color: Colors.black,
                                                  letterSpacing: 1.0,
                                                  fontSize: 14
                                              ),),
                                            )
                                          ],
                                        ),
                                      ),
                                    ],

                                  ),
                                ),
                              ],
                            ),
                            SizedBox(
                              height: 10,
                            ),
                            Divider(
                              color: Colors.grey[400],
                              thickness: 0.3,
                            ),
                            Align(
                              alignment: Alignment.topLeft,
                              child: Padding(
                                padding: EdgeInsets.only(left: 16.0,right: 16),
                                child: Text(
                                  "Max 2 lakhs per transaction | Total 50 lakhs per day Fee Rs 10 Per transaction ",
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    fontSize: 13,
                                    fontWeight: FontWeight.bold,
                                    color: Colors.black,
                                  ),
                                ),
                              ),
                            ),
                            Divider(
                              color: Colors.grey[700],
                              thickness: 0.3,
                            ),
                            Container(
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: <Widget>[
                                  Padding(
                                    padding: EdgeInsets.only(left: 16.0, top: 16),
                                    child: Text(
                                      "INR AMOUNT",
                                      style: TextStyle(
                                        fontSize: 12,
                                        color: Colors.grey[700],
                                      ),
                                    ),
                                  ),
                                  Padding(
                                    padding: EdgeInsets.only(left: 16.0, top: 16,right: 16),
                                    child: Text(
                                      "AVAILABLE BALANCE :                    ",
                                      style: TextStyle(
                                        fontSize: 12,
                                        color: Colors.grey[700],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 16, right: 16, top: 8),
                              child: TextField(
                                autocorrect: true,
                                autofocus: false,
                                decoration: new InputDecoration(
                                    border: new OutlineInputBorder(
                                      borderRadius: const BorderRadius.all(
                                        const Radius.circular(5.0),
                                      ),
                                    ),

                                    filled: true,
                                    hintStyle: new TextStyle(color: Colors.grey[400]),
                                    hintText: "0.00",
                                    fillColor: Colors.white70),
                              ),
                            ),
                            Align(
                              alignment: Alignment.topLeft,
                              child: Padding(
                                padding: EdgeInsets.only(left: 16.0, top: 16),
                                child: Text(
                                  "REMARKS",
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: Colors.grey[700],
                                  ),
                                ),
                              ),
                            ),
                            Container(
                              padding: const EdgeInsets.only(left: 16, right: 16, top: 8),

                              child: TextField(
                                autocorrect: true,
                                autofocus: false,
                                decoration: new InputDecoration(
                                    border: new OutlineInputBorder(
                                      borderRadius: const BorderRadius.all(
                                        const Radius.circular(5.0),
                                      ),
                                    ),
                                    filled: true,
                                    hintStyle: new TextStyle(color: Colors.grey[800]),
                                    fillColor: Colors.white70),
                              ),
                            ),
                            SizedBox(
                              width: double.infinity,
                              child: Container(
                                margin: EdgeInsets.only(top: 20),
                                padding: const EdgeInsets.all(16.0),
                                child: RaisedButton(
                                  child: Text(
                                    "WITHDRAW",
                                    style: TextStyle(color: Colors.white, fontSize: 15),
                                  ),
                                  color: Colors.red,
                                  onPressed: () {
                                    showModalBottomSheet(

                                      isScrollControlled: true,
                                      context: context,
                                      builder: (context) => Wrap(children: [Container(
                                        width: MediaQuery.of(context).size.width,
                                        height: MediaQuery.of(context).size.height/1.8,
                                        color: Colors.white,
                                        padding: EdgeInsets.all(10.0),
                                        child: SingleChildScrollView(
                                          child: Column(
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            children: <Widget>[
                                              GestureDetector(
                                                onTap: ()=> Navigator.pop(context),
                                                child: Container(
                                                  alignment: Alignment.topRight,
                                                  child: Icon(Icons.close,color: Colors.grey,),
                                                ),
                                              ),
                                              Card(
                                                margin: EdgeInsets.all(10),
                                                child: Column(
                                                  children: [
                                                    Padding(
                                                      padding: const EdgeInsets.all(8.0),
                                                      child: Align(
                                                        alignment: Alignment.topLeft,
                                                        child: Text(
                                                          "Withdraw amount",
                                                          textAlign: TextAlign.left,
                                                          style: TextStyle(
                                                              fontSize: 15,
                                                              color: Colors.blueAccent,
                                                              fontWeight: FontWeight.w400),
                                                        ),
                                                      ),
                                                    ),
                                                    Divider(color: Colors.grey,thickness: 0.3,),
                                                    SizedBox(
                                                      height: 10,
                                                    ),
                                                    Column(
                                                      children: [
                                                        Align(
                                                          alignment: Alignment.center,
                                                          child: Padding(
                                                            padding: EdgeInsets.only(left: 8.0, bottom: 10),
                                                            child: Text(
                                                              "0.00INR",
                                                              style: TextStyle(
                                                                  fontSize: 26,
                                                                  color: Colors.blue,
                                                                  fontWeight: FontWeight.w400),
                                                            ),
                                                          ),
                                                        ),
                                                        Align(
                                                          alignment: Alignment.center,
                                                          child: Padding(
                                                            padding: EdgeInsets.only(left: 16.0),
                                                            child: Text(
                                                              "Pay to bank ****1234",
                                                              style: TextStyle(
                                                                fontSize: 15,
                                                                color: Colors.grey[400],
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                        Padding(
                                                          padding: const EdgeInsets.only(
                                                              left: 60, right: 60, top: 8, bottom: 8),
                                                          child: TextField(
                                                            textAlign: TextAlign.center,
                                                            decoration: new InputDecoration(
                                                                filled: true,
                                                                hintStyle: new TextStyle(color: Colors.grey[400]),
                                                                hintText: "Enter Amount",
                                                                fillColor: Colors.white70),
                                                          ),
                                                        ),
                                                        Row(
                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                          children: [
                                                            new Container(
                                                              margin: const EdgeInsets.all(8.0),
                                                              padding: const EdgeInsets.all(3.0),
                                                              decoration: BoxDecoration(
                                                                  border: Border.all(color: Colors.grey[400]),
                                                                  borderRadius:
                                                                  BorderRadius.all(Radius.circular(10))),
                                                              child: Padding(
                                                                padding: const EdgeInsets.all(8.0),
                                                                child: Text("+ 1000 INR",style: TextStyle(color: Colors.grey[400]),),
                                                              ),
                                                            ),
                                                            new Container(
                                                              margin: const EdgeInsets.all(8.0),
                                                              padding: const EdgeInsets.all(3.0),
                                                              decoration: BoxDecoration(
                                                                  border: Border.all(color: Colors.grey[400]),
                                                                  borderRadius:
                                                                  BorderRadius.all(Radius.circular(10))),
                                                              child: Padding(
                                                                padding: const EdgeInsets.all(8.0),
                                                                child: Text("+ 5000 INR",style: TextStyle(color: Colors.grey[400]),),
                                                              ),
                                                            ),
                                                            new Container(
                                                              margin: const EdgeInsets.all(8.0),
                                                              padding: const EdgeInsets.all(3.0),
                                                              decoration: BoxDecoration(
                                                                  border: Border.all(color: Colors.grey[400]),
                                                                  borderRadius:
                                                                  BorderRadius.all(Radius.circular(10))),
                                                              child: Padding(
                                                                padding: const EdgeInsets.all(8.0),
                                                                child: Text("+ 10000 INR",style: TextStyle(color: Colors.grey[400]),),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ],
                                                    ),
                                                    SizedBox(
                                                      height: 20,
                                                    ),
                                                    Align(
                                                      alignment: Alignment.center,
                                                      child: Padding(
                                                        padding: EdgeInsets.only(left: 40.0,right: 40),
                                                        child: Text(
                                                          "10.00 INR will  be charged on every transaction",
                                                          maxLines: 3,
                                                          textAlign: TextAlign.center,
                                                          style: TextStyle(
                                                            fontSize: 15,
                                                            color: Colors.grey[400],
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Divider(
                                                      color: Colors.grey[700],
                                                    ),
                                                    SizedBox(
                                                      child: Padding(
                                                        padding: const EdgeInsets.all(8.0),
                                                        child: RaisedButton(
                                                          child: Padding(
                                                            padding: const EdgeInsets.all(8.0),
                                                            child: Text(
                                                              "Proceed to Withdraw",
                                                              style: TextStyle(color: Colors.white, fontSize: 18),
                                                            ),
                                                          ),
                                                          color: Colors.blue,
                                                          onPressed: () {
                                                            showDialog(
                                                                context: context,
                                                                builder: (BuildContext context) {
                                                                  return Dialog(

                                                                    shape: RoundedRectangleBorder(
                                                                        borderRadius:
                                                                        BorderRadius.circular(20.0)), //this right here
                                                                    child: Container(
                                                                      color: Colors.blueAccent,
                                                                      height: 250,
                                                                      child: Padding(
                                                                        padding: const EdgeInsets.all(15.0),
                                                                        child: Column(
                                                                          mainAxisAlignment: MainAxisAlignment.start,
                                                                          crossAxisAlignment: CrossAxisAlignment.start,
                                                                          children: [
                                                                            Text('Amount will be credited to your Below registered bank account',style: TextStyle(
                                                                                color: Colors.white,
                                                                                fontSize: 18
                                                                            ),),
                                                                            Container(
                                                                              margin: EdgeInsets.only(top: 20),
                                                                              child: Row(
                                                                                children: <Widget>[
                                                                                  Container(
                                                                                      child: Text('Bank name:  '
                                                                                        ,style: TextStyle(
                                                                                            color: Colors.white,
                                                                                            fontSize: 15
                                                                                        ),)),
                                                                                  Container(
                                                                                      child: Text('STATE BANK OF INDIA'
                                                                                        ,style: TextStyle(
                                                                                            color: Colors.white,
                                                                                            fontSize: 16
                                                                                        ),)),
                                                                                ],
                                                                              ),
                                                                            ),
                                                                            Container(
                                                                              alignment: Alignment.center,
                                                                              margin: EdgeInsets.only(top: 10),
                                                                              child: Row(
                                                                                children: <Widget>[
                                                                                  Container(
                                                                                      child: Text('Name:  '
                                                                                        ,style: TextStyle(
                                                                                            color: Colors.white,
                                                                                            fontSize: 15
                                                                                        ),)),
                                                                                  Container(
                                                                                      child: Text('Bank Withdrawal'
                                                                                        ,style: TextStyle(
                                                                                            color: Colors.white,
                                                                                            fontSize: 16
                                                                                        ),)),
                                                                                ],
                                                                              ),
                                                                            ),
                                                                            Container(
                                                                              margin: EdgeInsets.only(top: 10),
                                                                              child: Row(
                                                                                children: <Widget>[
                                                                                  Container(
                                                                                      child: Text('Account Number:  '
                                                                                        ,style: TextStyle(
                                                                                            color: Colors.white,
                                                                                            fontSize: 15
                                                                                        ),)),
                                                                                  Container(
                                                                                      child: Text('1275459658'
                                                                                        ,style: TextStyle(
                                                                                            color: Colors.white,
                                                                                            fontSize: 16
                                                                                        ),)),
                                                                                ],
                                                                              ),
                                                                            ),
                                                                            Container(
                                                                              margin: EdgeInsets.only(top: 15),
                                                                              child: Row(
                                                                                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                                                                                children: <Widget>[
                                                                                  Container(
                                                                                    child: RaisedButton(
                                                                                      onPressed: () {},
                                                                                      child: Text(
                                                                                        "Ok",
                                                                                        style: TextStyle(color: Colors.blueAccent,fontWeight: FontWeight.bold),
                                                                                      ),
                                                                                      color: Colors.white,
                                                                                    ),
                                                                                  ),
                                                                                  Container(
                                                                                    child: RaisedButton(
                                                                                      onPressed: () {
                                                                                        Navigator.pop(context);
                                                                                      },
                                                                                      child: Text(
                                                                                        "Cancle",
                                                                                        style: TextStyle(color: Colors.blueAccent,fontWeight: FontWeight.bold),
                                                                                      ),
                                                                                      color: Colors.white,
                                                                                    ),
                                                                                  )
                                                                                ],
                                                                              ),
                                                                            )
                                                                          ],
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  );
                                                                });
                                                          },
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),]),
                                    );
                                    /* Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => SecondWithdrawPage()),
                              );*/
                                  },
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                );
                //Text(snapshot.data.title);
              } else if (futureAlbum == null) {
                return GestureDetector(
                  onTap: (){
                    Navigator.pop(context);
                    Navigator.push(
                      context,
                      PageTransition(
                        type: PageTransitionType.leftToRight,
                        child: PaymentOption(),
                      ),
                    );
                  },
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: MediaQuery.of(context).size.height,
                    // color: Color(0xFF18222C),
                    child:  Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        Container(
                          width: 150,
                          alignment: Alignment.center,
                          padding: EdgeInsets.all(10),
                          child: Text(
                            'Add Bank Detail`s',
                            style: TextStyle(color: Colors.white, fontSize: 18,),
                          ),
                          decoration: BoxDecoration(
                              borderRadius: BorderRadius.all(Radius.circular(10)),
                              color: Colors.blue,
                              border: Border.all(color: Colors.blue)),
                        ),

                      ],
                    ),
                  ),
                );
              }

              else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }
              return Container(
                  alignment: Alignment.center,
                  height: MediaQuery.of(context).size.height,
                  width: MediaQuery.of(context).size.width,
                  // margin: EdgeInsets.only(top: 80),
                  child: CircularProgressIndicator(backgroundColor: Colors.white,));
            },
          )
      )

    );
  }
}
