import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:fyn_zon/deposit.dart';
import 'package:fyn_zon/tokenPass.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'custom_appbar.dart';
import 'mainApi.dart';

class Autogenerated {
  String message;
  String error;
  Data data;

  Autogenerated({this.message, this.error, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    error = json['error'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  Record record;

  Data({this.record});

  Data.fromJson(Map<String, dynamic> json) {
    record =
    json['record'] != null ? new Record.fromJson(json['record']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.record != null) {
      data['record'] = this.record.toJson();
    }
    return data;
  }
}

class Record {
  String sId;
  String country;
  int phone;
  String fname;
  String lname;
  String email;
  String accType;
  String bankAccNo;
  String ifscCode;
  String address;
  String city;
  String dob;
  String pinCode;
  String state;
  String nationality;
  String bankName;
  String imageURL;
  String area;
  String houseNo;
  String landmark;
  String streetName;

  Record(
      {this.sId,
        this.country,
        this.phone,
        this.fname,
        this.lname,
        this.email,
        this.accType,
        this.bankAccNo,
        this.ifscCode,
        this.address,
        this.city,
        this.dob,
        this.pinCode,
        this.state,
        this.nationality,
        this.bankName,
        this.imageURL,
        this.area,
        this.houseNo,
        this.landmark,
        this.streetName});

  Record.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    country = json['country'];
    phone = json['phone'];
    fname = json['fname'];
    lname = json['lname'];
    email = json['email'];
    accType = json['accType'];
    bankAccNo = json['bankAccNo'];
    ifscCode = json['ifscCode'];
    address = json['address'];
    city = json['city'];
    dob = json['dob'];
    pinCode = json['pinCode'];
    state = json['state'];
    nationality = json['nationality'];
    bankName = json['bank_name'];
    imageURL = json['image_URL'];
    area = json['area'];
    houseNo = json['house_no'];
    landmark = json['landmark'];
    streetName = json['street_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['country'] = this.country;
    data['phone'] = this.phone;
    data['fname'] = this.fname;
    data['lname'] = this.lname;
    data['email'] = this.email;
    data['accType'] = this.accType;
    data['bankAccNo'] = this.bankAccNo;
    data['ifscCode'] = this.ifscCode;
    data['address'] = this.address;
    data['city'] = this.city;
    data['dob'] = this.dob;
    data['pinCode'] = this.pinCode;
    data['state'] = this.state;
    data['nationality'] = this.nationality;
    data['bank_name'] = this.bankName;
    data['image_URL'] = this.imageURL;
    data['area'] = this.area;
    data['house_no'] = this.houseNo;
    data['landmark'] = this.landmark;
    data['street_name'] = this.streetName;
    return data;
  }
}
class InstantDeposit extends StatefulWidget {
  const InstantDeposit({Key key}) : super(key: key);

  @override
  _InstantDepositState createState() => _InstantDepositState();
}

class _InstantDepositState extends State<InstantDeposit> {


  @override
  void initState() {
    fetchAlbum1();
    super.initState();

  }
  Autogenerated userData;
  var userid;
  Future<void> fetchAlbum1() async {
    /* var data = {

    };*/
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      userid = prefs.getString('userid');
    });
    var apiData = {
      "url": AuthToken.api + "/" + "kyc/v2/userProfile/"+ prefs.getString('token'),
      //"data": data
    };
    ApiClass.getApiCall(apiData, (onSuccess) {
      print(onSuccess.toString());
      userData = Autogenerated.fromJson(jsonDecode(onSuccess['response']));
      //print("walletqrcode>>>>>>> " + futureAlbum.data.phone.toString());
      setState(() {});
    }, (onError) {
      print("Error working with the api");
    });
  }
  final GlobalKey<ScaffoldState> key = new GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: (){
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(
            builder: (context) => DepositPage(),
          ),
        );
      },
      child: Scaffold(
        key: key,
        appBar: appBar('Instant Deposit'),
        body: SingleChildScrollView(
          child: FutureBuilder<Autogenerated>(
            builder: (context, snapshot){
              if(userData != null){
                return SafeArea(
                  child: Padding(
                    padding: EdgeInsets.all(0),
                    child: Column(
                      children: <Widget>[
                        Container(
                          decoration: new BoxDecoration(
                            borderRadius: BorderRadius.only(bottomLeft: Radius.circular(40), bottomRight: Radius.circular(40)),
                            image: new DecorationImage(image: new AssetImage("assets/bg.png"), fit: BoxFit.cover,),
                          ),
                          height: MediaQuery.of(context).size.height /3,
                          width: MediaQuery.of(context).size.width,
                          child: Padding(
                            padding: EdgeInsets.all(10),
                            child: Column(
                              children: [
                                Text('To deposit funds, transfer from your Bank account to our account without a deposit order.',
                                  style: TextStyle(
                                      fontSize: 13,
                                      color: Colors.white,
                                      letterSpacing: 0.5,

                                  ),),
                                SizedBox(
                                  height: 30,
                                ),
                                Container(
                                  decoration: new BoxDecoration(
                                    borderRadius: BorderRadius.all(Radius.circular(15)),
                                    color: Colors.black
                                  ),
                                  child: Column(
                                    children: [
                                      Container(
                                        alignment: Alignment.topLeft,
                                        padding: EdgeInsets.fromLTRB(20, 20, 20, 10),
                                        child: Text('PAY FROM',
                                          style: TextStyle(
                                              fontSize: 20,
                                              color: Colors.white,
                                              letterSpacing: 0.5,
                                              fontWeight: FontWeight.w600
                                          ),),
                                      ),
                                      accountRow(),
                                    ],
                                  ),
                                )
                              ],
                            ),
                          ),
                        ),

                        Container(
                            alignment: Alignment.topLeft,
                            child: ListTile(
                              leading: Icon(Icons.food_bank,color: Colors.red,),
                              title: Transform.translate(
                                offset: Offset(-22, 0),
                                child: Text('Transfer money to this bank account using IMPS/NEFT/RTGS'.toUpperCase(),
                                  style: TextStyle(
                                      fontSize: 12,
                                      color: Colors.red,
                                      letterSpacing: 0.5,

                                  ),),
                              ),
                            )
                        ),

                        Padding(
                          padding: EdgeInsets.symmetric(horizontal: 15),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                Text('Beneficiary Name'.toUpperCase(),
                                textAlign: TextAlign.left,
                                style: TextStyle(
                                  fontSize: 12,
                                  color: Colors.grey[600],
                                 letterSpacing: 0.5,
                                 fontWeight: FontWeight.w600
                                  ),),
                                  Text('Virtual block innovations'.toUpperCase(),
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                        fontSize: 15,
                                        color: Colors.grey[800],
                                        letterSpacing: 0.5,
                                        fontWeight: FontWeight.w600
                                    ),),
                                ],
                              ),
                              GestureDetector(
                                  onTap: (){
    Clipboard.setData(new ClipboardData(text: "Virtual block innovations"));
    key.currentState.showSnackBar(
    new SnackBar(content: new Text("Copied to Clipboard"),));
    },
                                  child: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15)),
                            ],
                          ),
                        ),
                        SizedBox(
                          height: 15,
                        ),
                        Padding(
                          padding: EdgeInsets.symmetric(horizontal: 15),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text('BANK NAME',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                        fontSize: 12,
                                        color: Colors.grey[600],
                                        letterSpacing: 0.5,
                                        fontWeight: FontWeight.w600
                                    ),),
                                  Text('ICICI BANK',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                        fontSize: 15,
                                        color: Colors.grey[800],
                                        letterSpacing: 0.5,
                                        fontWeight: FontWeight.w600
                                    ),),
                                ],
                              ),
                              GestureDetector(
                                  onTap: (){
                                    Clipboard.setData(new ClipboardData(text: "ICICI BANK"));
                                    key.currentState.showSnackBar(
                                        new SnackBar(content: new Text("Copied to Clipboard"),));
                                  },
                                  child: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15)),
                            ],
                          ),
                        ),
                        SizedBox(
                          height: 15,
                        ),
                        Padding(
                          padding: EdgeInsets.symmetric(horizontal: 15),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text('ACCOUNT NUMBER',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                        fontSize: 12,
                                        color: Colors.grey[600],
                                        letterSpacing: 0.5,
                                        fontWeight: FontWeight.w600
                                    ),),
                                  Text('2648VB',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                        fontSize: 15,
                                        color: Colors.grey[800],
                                        letterSpacing: 0.5,
                                        fontWeight: FontWeight.w600
                                    ),),
                                ],
                              ),
                              GestureDetector(
                                  onTap: (){
                                    Clipboard.setData(new ClipboardData(text: "2648VB"));
                                    key.currentState.showSnackBar(
                                        new SnackBar(content: new Text("Copied to Clipboard"),));
                                  },
                                  child: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15)),
                            ],
                          ),
                        ),
                        SizedBox(
                          height: 15,
                        ),
                        Padding(
                          padding: EdgeInsets.symmetric(horizontal: 15),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text('IFSC CODE',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                        fontSize: 12,
                                        color: Colors.grey[600],
                                        letterSpacing: 0.5,
                                        fontWeight: FontWeight.w600
                                    ),),
                                  Text('ICIC0000106',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                        fontSize: 15,
                                        color: Colors.grey[800],
                                        letterSpacing: 0.5,
                                        fontWeight: FontWeight.w600
                                    ),),
                                ],
                              ),
                              GestureDetector(
                                  onTap: (){
                                    Clipboard.setData(new ClipboardData(text: "ICIC0000106"));
                                    key.currentState.showSnackBar(
                                        new SnackBar(content: new Text("Copied to Clipboard"),));
                                  },
                                  child: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15)),
                            ],
                          ),
                        ),
                        SizedBox(
                          height: 15,
                        ),
                        Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Card(
                            elevation: 2,
                            color: Colors.black87,
                            child: Padding(
                              padding: EdgeInsets.symmetric(horizontal: 20,vertical: 10),
                              child: Text("Visit our support page for steps on 'How to deposit instantly'",
                                style: TextStyle(
                                    fontSize: 14,
                                    color: Colors.white,
                                ),),
                            ),
                          ),
                        ),
                        SizedBox(
                          height: 15,
                        ),
                        Container(
                          alignment: Alignment.topLeft,
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Text('IMPORTANT',
                            style: TextStyle(
                                color: Colors.red,
                                fontSize: 18,
                                fontWeight: FontWeight.bold
                            ),),
                        ),
                        SizedBox(
                          height: 10,
                        ),
                        Container(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: SafeArea(
                            child: Text('IMPS, NEFT & available 24*7 | RTGS as per banking norms. Deposit only from your register bank account. You can not deposit from any other bank account',
                              style: TextStyle(
                                  fontSize: 15,
                                  color: Colors.black,
                                  fontWeight: FontWeight.w500
                              ),),
                          ),
                        ),

                      ],
                    ),
                  ),
                );
              }
              else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }
              return Container(
                  alignment: Alignment.center,
                  decoration: new BoxDecoration(
                    image: new DecorationImage(image: new AssetImage("assets/bg.png"), fit: BoxFit.cover,),
                  ),
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height,
                  // margin: EdgeInsets.only(top: 80),
                  child: CircularProgressIndicator(strokeWidth: 6.0,
                      backgroundColor: Colors.green,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.blue)));
            },
          )
        ),
      ),
    );
  }

  Widget accountRow(){
    return Container(
      alignment: Alignment.topLeft,
      padding: EdgeInsets.fromLTRB(20, 10, 20, 20),
      child: Row(
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          account(),
          account2()
        ],
      ),
    );
  }

  Widget account(){
    return Container(
alignment: Alignment.topLeft,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Container(
            alignment: Alignment.topLeft,
            child: Text('Account Number',
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.white,
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
          Container(
            padding: EdgeInsets.only(top: 10),
            alignment: Alignment.topLeft,
            child: Text('IFSC Code',
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.white,
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
          Padding(
            padding: EdgeInsets.only(top: 10),
            child: Text('Account Type',
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.white,
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
        ],
      ),
    );
  }
  Widget account2(){
    return Container(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text(userData.data.record.bankAccNo.toString(),
            style: TextStyle(
                fontSize: 15,
                color: Colors.white,
                letterSpacing: 0.5,
                fontWeight: FontWeight.w600
            ),),
          Padding(
            padding: EdgeInsets.only(top: 10),
            child: Text(userData.data.record.ifscCode.toString(),
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.white,
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
          Padding(
            padding: EdgeInsets.only(top: 10),
            child: Text(userData.data.record.accType.toString(),
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.white,
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
        ],
      ),
    );
  }

}
