import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:fyn_zon/tokenPass.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'Model/user_data_model.dart';
import 'mainApi.dart';
class InstantDeposit extends StatefulWidget {
  const InstantDeposit({Key key}) : super(key: key);

  @override
  _InstantDepositState createState() => _InstantDepositState();
}

class _InstantDepositState extends State<InstantDeposit> {


  @override
  void initState() {
    fetchAlbum1();
    super.initState();

  }
  Autogenerated userData;
  var userid;
  Future<void> fetchAlbum1() async {
    /* var data = {

    };*/
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      userid = prefs.getString('userid');
    });
    var apiData = {
      "url": AuthToken.api + "/" + "client/userDetails/"+ prefs.getString('token'),
      //"data": data
    };
    ApiClass.getApiCall(apiData, (onSuccess) {
      print(onSuccess.toString());
      userData = Autogenerated.fromJson(jsonDecode(onSuccess['response']));
      //print("walletqrcode>>>>>>> " + futureAlbum.data.phone.toString());
      setState(() {});
    }, (onError) {
      print("Error working with the api");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          backgroundColor: Color(0xFF18222C),
        title:Text('Instant Deposit')
      ),
      body: SingleChildScrollView(
        child: Container(
          padding: EdgeInsets.all(10),
          child: Column(
            children: <Widget>[
              Container(
                child: Text('To deposit funds, transfer from your Bank account to our account without a deposit order.',
                style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey[600],
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
                ),),
              ),
              Container(
                alignment: Alignment.topLeft,
                padding: EdgeInsets.fromLTRB(20, 20, 20, 10),
                child: Text('Pay From',
                  style: TextStyle(
                      fontSize: 20,
                      color: Colors.black87,
                      letterSpacing: 0.5,
                      fontWeight: FontWeight.w600
                  ),),
              ),
               accountRow(),
              Container(
                alignment: Alignment.topLeft,
                padding: EdgeInsets.fromLTRB(0, 20, 20, 0),
                child: ListTile(
                  leading: Icon(Icons.food_bank,color: Colors.red,),
                  title: Text('Transfer money to this bank account using IMPS/NEFT/RTGC',
                    style: TextStyle(
                        fontSize: 14,
                        color: Colors.red,
                        letterSpacing: 0.5,
                        fontWeight: FontWeight.w600
                    ),),
                )
              ),
              Container(
                  alignment: Alignment.topLeft,
                  padding: EdgeInsets.fromLTRB(0, 20, 20, 0),
                  child: ListTile(
                    trailing: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15,),
                    title: Text('Beneficiary Name',
                      style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey[600],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                    subtitle: Text('Virtual block innovations',
                      style: TextStyle(
                          fontSize: 15,
                          color: Colors.grey[800],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                  )
              ),
              Container(
                  alignment: Alignment.topLeft,
                  padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                  child: ListTile(
                    trailing: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15,),
                    title: Text('Bank Name',
                      style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey[600],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                    subtitle: Text('ICICI Bank',
                      style: TextStyle(
                          fontSize: 15,
                          color: Colors.grey[800],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                  )
              ),
              Container(
                  alignment: Alignment.topLeft,
                  padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                  child: ListTile(
                    trailing: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15,),
                    title: Text('Account Number',
                      style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey[600],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                    subtitle: Text('2648VB',
                      style: TextStyle(
                          fontSize: 15,
                          color: Colors.grey[800],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                  )
              ),
              Container(
                  alignment: Alignment.topLeft,
                  padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                  child: ListTile(
                    trailing: Icon(Icons.copy,color: Colors.lightBlueAccent,size: 15,),
                    title: Text('IFSC Code',
                      style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey[600],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                    subtitle: Text('ICICI000106',
                      style: TextStyle(
                          fontSize: 15,
                          color: Colors.grey[800],
                          letterSpacing: 0.5,
                          fontWeight: FontWeight.w600
                      ),),
                  )
              ),
              Container(
                child: Text('Visit our support page for steps on `How to deposit instantly`',
                  style: TextStyle(
                      fontSize: 15,
                      color: Colors.grey[600],
                      letterSpacing: 0.5,
                      fontWeight: FontWeight.w600
                  ),),
              ),
              Container(
                alignment: Alignment.topLeft,
                padding: EdgeInsets.only(top: 10),
                child: Text('Important',
                style: TextStyle(
                  color: Colors.red,
                  fontSize: 18,
                  fontWeight: FontWeight.bold
                ),),
              ),
              Container(
                padding: EdgeInsets.only(top: 20),
                child: SafeArea(
                  child: Text('IMPS, NEFT & available 24*7 | RTGC as per banking norms. Deposit only from your register bank account. You can not deposit from any other bank account',
                    style: TextStyle(
                        fontSize: 15,
                        color: Colors.grey[600],
                        letterSpacing: 0.5,
                        fontWeight: FontWeight.w600
                    ),),
                ),
              ),

            ],
          ),
        ),
      ),
    );
  }

  Widget accountRow(){
    return Container(
      alignment: Alignment.topLeft,
      padding: EdgeInsets.fromLTRB(20, 10, 20, 20),
      child: Row(
    mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          account(),
          account2()
        ],
      ),
    );
  }

  Widget account(){
    return Container(
alignment: Alignment.topLeft,
      child: Column(
        children: <Widget>[
          Container(

            alignment: Alignment.topLeft,
            child: Text('Account Number',
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey[600],
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
          Container(
            padding: EdgeInsets.only(top: 10),
            alignment: Alignment.topLeft,
            child: Text('IFSC Code',
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey[600],
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
          Padding(
            padding: EdgeInsets.only(top: 10),
            child: Text('Account Type',
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey[600],
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
        ],
      ),
    );
  }
  Widget account2(){
    return Container(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          Text(userData.data.bankAccNo.toString(),
            style: TextStyle(
                fontSize: 15,
                color: Colors.grey[600],
                letterSpacing: 0.5,
                fontWeight: FontWeight.w600
            ),),
          Padding(
            padding: EdgeInsets.only(top: 10),
            child: Text(userData.data.ifscCode.toString(),
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey[600],
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
          Padding(
            padding: EdgeInsets.only(top: 10),
            child: Text(userData.data.accType.toString(),
              style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey[600],
                  letterSpacing: 0.5,
                  fontWeight: FontWeight.w600
              ),),
          ),
        ],
      ),
    );
  }

}
