import 'dart:convert';
import 'package:fyn_zon/inrTab_Deposit_Withdraw,dart.dart';
import 'package:fyn_zon/walletCurrencyQRCode.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:fyn_zon/tokenPass.dart';
import 'package:page_transition/page_transition.dart';
import 'package:fyn_zon/login.dart';
import 'package:fyn_zon/animation/FadeAnimation.dart';
import 'mainApi.dart';

class Autogenerated {
  String message;
  String error;
  Data data;

  Autogenerated({this.message, this.error, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    error = json['error'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  String sId;
  var bTCBalance;
  var eTHBalance;
  var uSDTBalance;
  var iNRBalance;
  var bCHBalance;
  var cRMTBalance;

  Data(
      {this.sId,
      this.bTCBalance,
      this.eTHBalance,
      this.uSDTBalance,
      this.iNRBalance,
      this.bCHBalance,
      this.cRMTBalance});

  Data.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    bTCBalance = json['BTCBalance'];
    eTHBalance = json['ETHBalance'];
    uSDTBalance = json['USDTBalance'];
    iNRBalance = json['INRBalance'];
    bCHBalance = json['BCHBalance'];
    cRMTBalance = json['CRMTBalance'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['BTCBalance'] = this.bTCBalance;
    data['ETHBalance'] = this.eTHBalance;
    data['USDTBalance'] = this.uSDTBalance;
    data['INRBalance'] = this.iNRBalance;
    data['BCHBalance'] = this.bCHBalance;
    data['CRMTBalance'] = this.cRMTBalance;
    return data;
  }
}

class Wallet extends StatefulWidget {
  @override
  _WalletState createState() => _WalletState();
}

class _WalletState extends State<Wallet> {
  Autogenerated futureAlbum;
  var userid;
  @override
  void initState() {
    fetchAlbum();

    super.initState();

  }
  Future<void> logout() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    // prefs?.clear();
    prefs.remove('token');
    prefs.remove('userid');
    Fluttertoast.showToast(
        msg: "User Logout",
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
        timeInSecForIosWeb: 1
    );
    Navigator.pop(context);
    Navigator.pushReplacement(
      context,
      PageTransition(
        type: PageTransitionType.leftToRight,
        child: LoginScreen(),
      ),
    );
        (Route route) => false;
  }

  fetchAlbum() async {
    /* var data = {

    };*/
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      userid = prefs.getString("userid");
    });
    var apiData = {
      "url": AuthToken.api +
          "/" +
          "getBalance/" +
          prefs.getString('token') +
          "/" +
          prefs.getString('userid'),
      //"data": data
    };
    ApiClass.getApiCall(apiData, (onSuccess) {
      print(onSuccess.toString());
      futureAlbum = Autogenerated.fromJson(jsonDecode(onSuccess['response']));
      print("wallet>>>>>>> " + futureAlbum.data.eTHBalance.toString());
      setState(() {});
    }, (onError) {
      print("Error working with the api");
      logout();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor:  Color(0xFF203040),
      /*  appBar: AppBar(
          title: Text('Wallet'),
          centerTitle: true,
          backgroundColor: Color(0xFF18222C),
        ),*/
        body: FadeAnimation(

          0.0, userid == null ?
          GestureDetector(
            onTap: (){
              Navigator.pop(context);
              Navigator.push(
                context,
                PageTransition(
                  type: PageTransitionType.leftToRight,
                  child: LoginScreen(),
                ),
              );
            },
            child: Container(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
             // color: Color(0xFF18222C),
              child:  Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Container(
                    width: 100,
                    alignment: Alignment.center,
                    padding: EdgeInsets.all(10),
                    child: Text(
                      'Login ',
                      style: TextStyle(color: Colors.white, fontSize: 18,),
                    ),
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.all(Radius.circular(10)),
                        color: Colors.blue,
                        border: Border.all(color: Colors.blue)),
                  ),

                ],
              ),
            ),
          ):
          SingleChildScrollView(
              child: FutureBuilder<Autogenerated>(
            //future: futureAlbum,
            builder: (context, snapshot) {
              if (futureAlbum != null) {
                return Container(
                 alignment: Alignment.center,
                   color: Color(0xFF203040),
                  //color: Colors.white,
                  //padding: EdgeInsets.all(10.0),
                  width: double.infinity,
                  child: SafeArea(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        GestureDetector(
                          onTap: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => WalletCurrencyQRCode( currncy: "ETH",),
                              ),
                            );
                          },
                          child: FadeAnimation(
                            0, Card(
                              margin: EdgeInsets.only(top: 1),
                              child: Container(
                                color: Color(0xFF18222C),
                                child: ListTile(
                                  leading: Image.asset("./assets/images/fz_eth.png"),
                                  title: Text(
                                    'Ethereum',
                                    style: TextStyle(
                                      color: Colors.white,
                                    ),
                                  ),
                                  subtitle: Row(
                                    children: <Widget>[
                                      Container(
                                        child: Text(
                                          futureAlbum.data.eTHBalance.toString(),
                                          style: TextStyle(
                                            color: Colors.white,
                                          ),
                                        ),
                                      ),
                                      Container(
                                        child: Text(
                                          ' ETH',
                                          style: TextStyle(
                                            color: Colors.white,
                                          ),
                                        ),
                                      )
                                    ],
                                  ),
                                  trailing: Text(
                                    'ETH',
                                    style: TextStyle(
                                      color: Colors.white,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),

                        GestureDetector(
                          onTap: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => InrTab(),
                              ),
                            );
                          },
                          child: FadeAnimation(
                            0, Card(
                              margin: EdgeInsets.only(top: 1),
                              child: Container(
                                color: Color(0xFF18222C),
                                child: ListTile(
                                  leading: Image.asset("./assets/images/inr icon.png"),
                                  title: Text(
                                    'Indian rupee',
                                    style: TextStyle(
                                      color: Colors.white,
                                    ),
                                  ),
                                  subtitle: Row(
                                    children: <Widget>[
                                      Container(
                                        child: Text(
                                          futureAlbum.data.iNRBalance.toString(),
                                          style: TextStyle(
                                            color: Colors.white,
                                          ),
                                        ),
                                      ),
                                      Container(
                                        child: Text(
                                          ' INR',
                                          style: TextStyle(
                                            color: Colors.white,
                                          ),
                                        ),
                                      )
                                    ],
                                  ),
                                  trailing: Text(
                                    'INR',
                                    style: TextStyle(
                                      color: Colors.white,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        )
                      ],
                    ),
                  ),
                );
                //Text(snapshot.data.title);
              } else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }
              return Container(
                  alignment: Alignment.center,
                  height: MediaQuery.of(context).size.height,
                  width: MediaQuery.of(context).size.width,
                  // margin: EdgeInsets.only(top: 80),
                  child: CircularProgressIndicator(backgroundColor: Colors.white,));
            },
          )
          ),
        )
    );

  }
}
