import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/material.dart';
import 'package:fyn_zon/btcwalletQRCode.dart';
import 'package:fyn_zon/tokenPass.dart';
import 'package:page_transition/page_transition.dart';
import 'package:fyn_zon/login.dart';
import 'package:fyn_zon/usdtwalletQRCode.dart';
import 'package:fyn_zon/animation/FadeAnimation.dart';
import 'bchwalletQRCode.dart';
import 'crmtwalletQRCode.dart';
import 'ethwalletQRCode.dart';
import 'mainApi.dart';

class Autogenerated {
  String message;
  String error;
  Data data;

  Autogenerated({this.message, this.error, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    error = json['error'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  String sId;
  var bTCBalance;
  var eTHBalance;
  var uSDTBalance;
  var iNRBalance;
  var bCHBalance;
  var cRMTBalance;

  Data(
      {this.sId,
      this.bTCBalance,
      this.eTHBalance,
      this.uSDTBalance,
      this.iNRBalance,
      this.bCHBalance,
      this.cRMTBalance});

  Data.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    bTCBalance = json['BTCBalance'];
    eTHBalance = json['ETHBalance'];
    uSDTBalance = json['USDTBalance'];
    iNRBalance = json['INRBalance'];
    bCHBalance = json['BCHBalance'];
    cRMTBalance = json['CRMTBalance'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['BTCBalance'] = this.bTCBalance;
    data['ETHBalance'] = this.eTHBalance;
    data['USDTBalance'] = this.uSDTBalance;
    data['INRBalance'] = this.iNRBalance;
    data['BCHBalance'] = this.bCHBalance;
    data['CRMTBalance'] = this.cRMTBalance;
    return data;
  }
}

class Wallet extends StatefulWidget {
  @override
  _WalletState createState() => _WalletState();
}

class _WalletState extends State<Wallet> {
  Autogenerated futureAlbum;

  @override
  void initState() {
    super.initState();
    fetchAlbum();
  }

  fetchAlbum() async {
    /* var data = {

    };*/
    var prefs = await SharedPreferences.getInstance();
    var user = prefs.getString("userid");
    AuthToken.userid = user;
    var token = prefs.getString("token");
    AuthToken.authtoken = token;
    var apiData = {
      "url": AuthToken.api +
          "/" +
          "getBalance/" +
          AuthToken.authtoken +
          "/" +
          AuthToken.userid,
      //"data": data
    };
    ApiClass.getApiCall(apiData, (onSuccess) {
      print(onSuccess.toString());
      futureAlbum = Autogenerated.fromJson(jsonDecode(onSuccess['response']));
      print("wallet>>>>>>> " + futureAlbum.data.eTHBalance.toString());
      setState(() {});
    }, (onError) {
      print("Error working with the api");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor:  Color(0xFF203040),
        appBar: AppBar(
          title: Text('Wallet'),
          backgroundColor: Color(0xFF18222C),
        ),
        body: AuthToken.userid == null ?
        GestureDetector(
          onTap: (){
            Navigator.pop(context);
            Navigator.push(
              context,
              PageTransition(
                type: PageTransitionType.leftToRight,
                child: LoginScreen(),
              ),
            );
          },
          child: Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
           // color: Color(0xFF18222C),
            child:  Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Container(
                  width: 100,
                  alignment: Alignment.center,
                  padding: EdgeInsets.all(10),
                  child: Text(
                    'Login ',
                    style: TextStyle(color: Colors.white, fontSize: 18,),
                  ),
                  decoration: BoxDecoration(
                      borderRadius: BorderRadius.all(Radius.circular(10)),
                      color: Colors.blue,
                      border: Border.all(color: Colors.blue)),
                ),

              ],
            ),
          ),
        ):
        SingleChildScrollView(
            child: FutureBuilder<Autogenerated>(
          //future: futureAlbum,
          builder: (context, snapshot) {
            if (futureAlbum != null) {
              return Container(
                 color: Color(0xFF203040),
                //color: Colors.white,
                //padding: EdgeInsets.all(10.0),
                width: double.infinity,
                child: Column(
                  children: <Widget>[
                    GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => WalletQRCode(),
                          ),
                        );
                      },
                      child: FadeAnimation(
                        2.5,
                         Card(
                          margin: EdgeInsets.only(top: 1),
                          child: Container(
                            color: Color(0xFF18222C),
                            child: ListTile(
                              leading: Image.asset("./assets/images/fz_btc.png"),
                              title: Text(
                                'Bitcoin',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                              subtitle: Row(
                                children: <Widget>[
                                  Container(
                                    child: Text(
                                      futureAlbum.data.bTCBalance.toString(),
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  Container(
                                    child: Text(
                                      ' BTC',
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  )
                                ],
                              ),
                              trailing: Text(
                                'BTC',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => BCHWalletQRCode(),
                          ),
                        );
                      },
                      child:  FadeAnimation(
                        2.5, Card(
                          margin: EdgeInsets.only(top: 1),
                          child: Container(
                            color: Color(0xFF18222C),
                            child: ListTile(
                              leading: Image.asset("./assets/images/fz_bch.png"),
                              title: Text(
                                'Bitcoin Cash',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                              subtitle: Row(
                                children: <Widget>[
                                  Container(
                                    child: Text(
                                      futureAlbum.data.bCHBalance.toString(),
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  Container(
                                    child: Text(
                                      ' BCH',
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  )
                                ],
                              ),
                              trailing: Text(
                                'BCH',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => ETHWalletQRCode(),
                          ),
                        );
                      },
                      child: FadeAnimation(
                        2.5, Card(
                          margin: EdgeInsets.only(top: 1),
                          child: Container(
                            color: Color(0xFF18222C),
                            child: ListTile(
                              leading: Image.asset("./assets/images/fz_eth.png"),
                              title: Text(
                                'Ethereum',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                              subtitle: Row(
                                children: <Widget>[
                                  Container(
                                    child: Text(
                                      futureAlbum.data.eTHBalance.toString(),
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  Container(
                                    child: Text(
                                      ' ETH',
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  )
                                ],
                              ),
                              trailing: Text(
                                'ETH',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => USDTWalletQRCode(),
                          ),
                        );
                      },
                      child: FadeAnimation(
                        2.5, Card(
                          margin: EdgeInsets.only(top: 1),
                          child: Container(
                            color: Color(0xFF18222C),
                            child: ListTile(
                              leading: Image.asset("./assets/images/fz_usdt.png"),
                              title: Text(
                                'Tether',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                              subtitle: Row(
                                children: <Widget>[
                                  Container(
                                    child: Text(
                                      futureAlbum.data.uSDTBalance.toString(),
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  Container(
                                    child: Text(
                                      ' USDT',
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  )
                                ],
                              ),
                              trailing: Text(
                                'USDT',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => CRMTWalletQRCode(),
                          ),
                        );
                      },
                      child: FadeAnimation(
                        2.5, Card(
                          margin: EdgeInsets.only(top: 1),
                          child: Container(
                            color: Color(0xFF18222C),
                            child: ListTile(
                              leading: Image.asset("./assets/images/fz_crmt.png"),
                              title: Text(
                                'Cremit',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                              subtitle: Row(
                                children: <Widget>[
                                  Container(
                                    child: Text(
                                      futureAlbum.data.cRMTBalance.toString(),
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  Container(
                                    child: Text(
                                      ' CRMT',
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  )
                                ],
                              ),
                              trailing: Text(
                                'CRMT',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => CRMTWalletQRCode(),
                          ),
                        );
                      },
                      child: FadeAnimation(
                        2.5, Card(
                          margin: EdgeInsets.only(top: 1),
                          child: Container(
                            color: Color(0xFF18222C),
                            child: ListTile(
                              leading: Image.asset("./assets/images/fz_crmt.png"),
                              title: Text(
                                'Indian rupee',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                              subtitle: Row(
                                children: <Widget>[
                                  Container(
                                    child: Text(
                                      futureAlbum.data.iNRBalance.toString(),
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  Container(
                                    child: Text(
                                      ' INR',
                                      style: TextStyle(
                                        color: Colors.white,
                                      ),
                                    ),
                                  )
                                ],
                              ),
                              trailing: Text(
                                'INR',
                                style: TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    )
                  ],
                ),
              );
              //Text(snapshot.data.title);
            } else if (snapshot.hasError) {
              return Text("${snapshot.error}");
            }
            return Container(
                alignment: Alignment.center,
                height: MediaQuery.of(context).size.height,
                width: MediaQuery.of(context).size.width,
                // margin: EdgeInsets.only(top: 80),
                child: CircularProgressIndicator(backgroundColor: Colors.white,));
          },
        )
        )
    );

  }
}
